### ISSUE TITLE
DRMIME google colab notebook

### ISSUE THREAD

**Issue by guijacquemet** [abnan/DRMIME#1]
Hi,

Thanks for providing this great tool! We are now using it in the lab to align images of [Zebrafish embryo](https://twitter.com/guijacquemet/status/1358851660450304004).

I just wanted to let you know that I made a Google Colab notebook of your software for the [ZeroCostDL4Mic](https://github.com/HenriquesLab/ZeroCostDL4Mic) project.
The notebook is available [here](https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki) in case you are interested.

All the best

Guillaume

**Comment by abnan** [comment]
Thank you, happy to know you found it useful!
